from .Fishing.barbarian_fishing import OSRSBarbFishing
from .Combat.NMZ import OSRSnmz
from .Woodcutting.Woodcutting import OSRSWoodcutting
from .Fishing.Karambwan import OSRSKarambwan
from .Fishing.Karambwanji import OSRSKarambwanji
from .Runecrafting.Blood_Runes_New import OSRSBloods
from .Mining.sandstone import OSRSSandstone
from .Agility.Seers_Agility import OSRSSeers
from .Herblore.Potions import OSRSPotions
from .Testing.template import OSRSTemplate